Adds call to python

diff --git a/bin/scua b/bin/scua
--- a/bin/scua
+++ b/bin/scua
@@ -30,7 +30,7 @@
 #
 
 # Paths to Python utilities
-SCUA_PYTHON=""
+SCUA_PYTHON="scua.py"
 SACCT_BASE_OPTS="--format JobIDRaw,JobName%30,Account,NNodes,NTasks,ElapsedRaw,State -P --delimiter ','"
 SACCT_OUTPUT_FILE="scua_sacct.txt"
 
@@ -80,6 +80,20 @@ then
    extra_opts="-a"
 fi
 sacct ${startdate} ${enddate} ${extra_opts} ${SACCT_BASE_OPTS} | egrep '[0-9]\.[0-9]' | grep COMPLETED > scua_sacct.txt
+if [ $? > 0 ]
+then
+   echo "Error - sacct did not complete correctly" 1>&2
+   exit 1
+fi
+if [ -s scua_sacct.txt ]
+then
+   # We have some data, lets process it
+   ${SCUA_PYTHON} scua_sacct.txt
+else
+   # No data, just stop
+   echo "No jobs found"
+fi
 
+rm scua_sacct.txt
 exit 0
 
